#########################
# Setup:
# At  Sun 29 May EEST 2022 there still bug (  ) in wg-easy package so need little patch:
# find /var/lib/docker/overlay2/ -type f -name WireGuard.js -exec sed -i 's/ListenPort \= 51820/ListenPort \= \$\{WG_PORT\}/g' {} \;
# - apply this patch after docker-compose first init ( its required image to download and install ).
#
# Web access:
# http://10.99.97.1:3000 - Adguard admin panel & first setup required.
# http://10.99.97.1:51821 - Wireguard admin panel.
#
# Desc:
# ...
#
#########################

version: "3.8"
services:
#
# Service -- wireguard
#
  wg-easy:
    image: weejewel/wg-easy:nightly
    container_name: wg-easy
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./etc_wireguard:/etc/wireguard
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=<<__PUBLIC:_IP.IP.IP.IP_____________OR__________YOUR.DNS.ADDRESS.LOCALHOST.COM_____>>>
      - PASSWORD=<<____CHANGE_ME_MIZDSMJRGAYTEMBSGQ2TKNJRG5RDGZDBGI4TOOLCGI4WK_CHANGE_ME_____>>
      # Optional:
      - WG_PORT=47777
      - WG_DEFAULT_ADDRESS=10.99.97.x
      - WG_DEFAULT_DNS=1.1.1.3,45.90.28.147,9.9.9.9,1.0.0.3
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.99.97.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 47120 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A PREROUTING -i wg0 -p tcp --dport 53 -j REDIRECT;iptables -t nat -A PREROUTING -i wg0 -p udp --dport 53 -j REDIRECT; iptables --append FORWARD --src 10.99.97.0/24 --dst 10.99.97.0/24 --jump DROP
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
#    ports:
#      - "51820:51820/udp"
#      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.all.src_valid_mark=1
    network_mode: "host"

#
# Service -- DNS
#
  DNS:
    image: adguard/adguardhome:edge
    container_name: adguardhome
    restart: unless-stopped
    pull_policy: always
    volumes:
        - './DNS_workdir:/opt/adguardhome/work'
        - './DNS_confdir:/opt/adguardhome/conf'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.all.src_valid_mark=1
    network_mode: "host"
        # ports:
    #     - '53:53/tcp'
    #     - '53:53/udp'
    #     - '67:67/udp'
    #     - '68:68/udp'
    #     - '80:80/tcp'
    #     - '443:443/tcp'
    #     - '443:443/udp'
    #     - '3000:3000/tcp'
    #     - '853:853/tcp'
    #     - '784:784/udp'
    #     - '853:853/udp'
    #     - '8853:8853/udp'
    #     - '5443:5443/tcp'
    #     - '5443:5443/udp'
